### ISSUE TITLE
Длинна заголовков

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGateWiki#5]
https://github.com/NorthGateVologda/NorthGateWiki/blob/727117a5e59ef9d4324894a1907b038a2348cd72/ENVIRONMENT.md?plain=1#L5

Дабы длинна строки в README не превышала 80 символов, предлагаю уменьшать длину заголовков, так как в содержании строка удваивается.

**Comment by olgapshen** [comment]
Все согласны?

**Comment by Marwin887** [comment]
@olgapshen Да

**Comment by olgapshen** [comment]
Подождём, когда все отпишутся и закроем :)

**Comment by lvapl** [comment]
Да, согласен

**Comment by olgapshen** [comment]
Ждём ещё два подтверждения.

**Comment by sshiae** [comment]
Согласен

**Comment by olgapshen** [comment]
Остался только @Malaxov16

**Comment by olgapshen** [comment]
Основная задача: https://github.com/NorthGateVologda/NorthGate/issues/42

**Comment by Malaxov16** [comment]
Согласен

**Comment by olgapshen** [comment]
@sshiae @lvapl @Malaxov16 @Marwin887 мы сделали это! Маленький шаг для стандартизации документации громадный шаг для проекта!
