### ISSUE TITLE
Длинна строки в 80 символов

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGateWiki#6]
https://github.com/NorthGateVologda/NorthGateWiki/blob/727117a5e59ef9d4324894a1907b038a2348cd72/ENVIRONMENT.md?plain=1#L16

Предлагаю обсудить регламент на длину строки в 80 символов. При отображении результата Markdown-а все строки между
которыми нет пустой строки или которые не оканчиваются на два пробела всё равно сливаются.

**Comment by olgapshen** [comment]
Все согласны?

**Comment by sshiae** [comment]
Согласен

**Comment by olgapshen** [comment]
> Согласен

Тут плюс в том, что очень удобно редактировать.
Ещё три подтверждения! @lvapl @Malaxov16 @Marwin887

**Comment by olgapshen** [comment]
Основная задача: https://github.com/NorthGateVologda/NorthGate/issues/42

**Comment by Marwin887** [comment]
@olgapshen Мне не понятен контекс, для чего, где и какие есть альтернативы?

**Comment by olgapshen** [comment]
> @olgapshen Мне не понятен контекс, для чего, где и какие есть альтернативы?

Это прекрасно, что ты спрашиваешь!

* Контекст: код на `Markdown`-е, то бишь всяческие `README`
* Альтернатива: не ограничивать длину строки

Теперь: зачем? Это хорошо для редактирования кода на `MD` (`Markdown`):

* Весь текст красиво выстраивается в параграф
* Не прыгает при изменении ширины окна
* Ширину окна часто нужно менять для параллельного просмотра результата
* Удобнее редактировать в `VIM` и прочих консольных редакторах

Это кстати не только для `MD` это хорошо для любого кода, особенно исполняемого, так как его можно легко менять в том же `VIM`-е на хосте как это было в ночь ~~перед рождеством~~ сдачей `MVP` на второй этап.

**Comment by lvapl** [comment]
Да, согласен

**Comment by olgapshen** [comment]
Супер! Остались @Malaxov16 и @Marwin887 
Я чувствую себя учительницей в школе, ожидающей домашнее задание :)

**Comment by Malaxov16** [comment]
Согласен

**Comment by olgapshen** [comment]
Остался @Marwin887

**Comment by olgapshen** [comment]
@Marwin887 ? Это последняя задача из цикла  `Расписаться` :) Если мы уважим богов феншуя и Markdown-а, то они помогут на пройти в самый финал :)

**Comment by Marwin887** [comment]
@olgapshen Я согласен
