### ISSUE TITLE
Таблицы из плагина VSCode

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGateWiki#7]
https://github.com/NorthGateVologda/NorthGateWiki/blob/727117a5e59ef9d4324894a1907b038a2348cd72/ENVIRONMENT.md?plain=1#L21

Предлагаю использовать таблицы из плагина VSCode - *Markdown All in one*.

![изображение](https://github.com/NorthGateVologda/NorthGateWiki/assets/13800244/dc4d3d82-aad6-4eaa-9852-09195a7e6e3b)

**Comment by olgapshen** [comment]
Все согласны?

**Comment by sshiae** [comment]
Вот тут на 100% согласен

**Comment by olgapshen** [comment]
> Вот тут на 100% согласен

Супер! Ещё три подтверждения :) @Malaxov16 @Marwin887 @lvapl

**Comment by olgapshen** [comment]
Основная задача: https://github.com/NorthGateVologda/NorthGate/issues/42

**Comment by Marwin887** [comment]
@olgapshen Мне не понятен контекс, для чего, где и какие есть альтернативы?

**Comment by olgapshen** [comment]
> @olgapshen Мне не понятен контекс, для чего, где и какие есть альтернативы?

Прекрасно, что ты спрашиваешь!!!

* Контекст: код на `Markdown`-е, то бишь всяческие `README`
* Альтернатива: использовать `HTML` форматирование от `GitHub`-а

Зачем? При форматировании через таблицы `MD` код очень нагляден и переносим. Так же можно легко просматривать через консольные редакторы типа `VIM` как это было в ночь ~~перед рождеством~~ сдачей MVP на второй этап.

**Comment by olgapshen** [comment]
Ещё три подтверждения. @Malaxov16 @Marwin887 @lvapl

**Comment by Marwin887** [comment]
@olgapshen Я согласен

**Comment by olgapshen** [comment]
Ещё два подтверждения. @Malaxov16 @lvapl

**Comment by lvapl** [comment]
Тоже согласен

**Comment by Malaxov16** [comment]
Согласен

**Comment by olgapshen** [comment]
Супер! Внесу в стандарты кода.
