### ISSUE TITLE
Картинки в MD

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGateWiki#8]
https://github.com/NorthGateVologda/NorthGateWiki/blob/727117a5e59ef9d4324894a1907b038a2348cd72/ENVIRONMENT.md?plain=1#L144

Предлагаю интегрировать картинки в сам репозиторий через папку `img/` и ссылки на неё в стиле `![Name](path)`.

Плюсы:

* Переносимость репозитория
* Инкапсуляция данных в репозитории
* Доступность файлов на случай недоступности GitHub-а

**Comment by olgapshen** [comment]
Все согласны?

**Comment by lvapl** [comment]
Да

**Comment by olgapshen** [comment]
Ждём ещё три подтверждения.

**Comment by sshiae** [comment]
Я согласен

**Comment by olgapshen** [comment]
Ещё два подтверждения :)

**Comment by olgapshen** [comment]
Основная задача: https://github.com/NorthGateVologda/NorthGate/issues/42

**Comment by Marwin887** [comment]
@olgapshen Мне не понятен контекс, для чего, где и какие есть альтернативы?

**Comment by olgapshen** [comment]
> @olgapshen Мне не понятен контекс, для чего, где и какие есть альтернативы?

Прекрасно, что ты спрашиваешь!!!

* Контекст: код на `Markdown`-е, то бишь всяческие `README`
* Альтернатива: использовать `HTML` интеграцию картинок от `GitHub`-а

Зачем? При использовании интегрированных картинок через `HTML` не удобно редактировать в ручную, а главное что репозиторий становится совершенно не портируемым, так как все бинарники остаются на хосте `GitHub`-а.

**Comment by olgapshen** [comment]
Ещё два подтверждения. @Malaxov16 @Marwin887

**Comment by Marwin887** [comment]
@olgapshen Я согласен

**Comment by olgapshen** [comment]
Остался @Malaxov16

**Comment by Malaxov16** [comment]
Согласен

**Comment by olgapshen** [comment]
Супер! Внесу в стандарты кода.
