### ISSUE TITLE
Наличие .code-workspace

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGateWiki#9]
Предлагаю ввести регламент наличия в каждом репозитории файла `.code-workspace`.
Думаю это целесообразно, так как в любом случае, как я понимаю, мы все используем `VSCode`, а в файле проекта `.code-workspace` можно прописать всю необходимую конфигурацию для актуальных плагинов.

**Comment by olgapshen** [comment]
Все согласны?

**Comment by lvapl** [comment]
Я не так часто использую VS Code. Но в целом не против

**Comment by olgapshen** [comment]
Ждём ещё три подтверждения.

**Comment by sshiae** [comment]
Тоже почти не использую VS COde, но мне без разницы

**Comment by olgapshen** [comment]
Ещё два подтверждения. @Malaxov16 @Marwin887

**Comment by olgapshen** [comment]
Основная задача: https://github.com/NorthGateVologda/NorthGate/issues/42

**Comment by Marwin887** [comment]
@olgapshen Мне не понятен контекс, для чего, где и какие есть альтернативы?

**Comment by olgapshen** [comment]
> @olgapshen Мне не понятен контекс, для чего, где и какие есть альтернативы?

Прекрасно, что ты спрашиваешь!!!

* Контекст: любые репозитрии нашего проекта
* Альтернатива: не сохранять `.code-workspace`

Зачем? Несмотря на то, что многие используют `IntellJ`, а не `VSCode` я всё же предлагаю сохранять проектальные файлы именно `VSCode`, ибо `VSCode` бесплатный, обладает достаточными возможностями и так же как `IntellJ` очень `Linux` ориентирован.

**Comment by olgapshen** [comment]
Ещё два подтверждения. @Malaxov16 @Marwin887

**Comment by Marwin887** [comment]
@olgapshen Я согласен

**Comment by olgapshen** [comment]
Остался @Malaxov16

**Comment by Malaxov16** [comment]
@olgapshen согласен

**Comment by olgapshen** [comment]
Супер! Потом внесу в стандарты кода.
